'use strict';
const {NodeOperationError}=require('n8n-workflow');
const runtime=require('../../runtime.cjs');
class Ultrabrain {
  constructor() {
    this.description={displayName:'Ultrabrain',name:'ultrabrain',icon:'fa:brain',group:['transform'],version:1,
      description:'Retrieve governed Agent memory and explicitly save consented turns through authenticated MCP',
      defaults:{name:'Ultrabrain'},inputs:['main'],outputs:['main'],usableAsTool:false,
      credentials:[{name:'ultrabrainApi',required:true}],
      properties:[
        {displayName:'Operation',name:'operation',type:'options',default:'before_turn',noDataExpression:true,
          options:[{name:'Check Connection',value:'identity',action:'Check the authenticated identity'},
            {name:'Get Personal Memory Overview',value:'personal_overview',action:'Read owner-wide memory statistics'},
            {name:'List Personal Candidates',value:'personal_candidates',action:'Read one scoped page of owned candidate metadata'},
            {name:'Inspect Personal Memory',value:'personal_inspect',action:'Read and verify one owned memory with explicit text disclosure'},
            {name:'Verify Personal Memory Source',value:'personal_lineage',action:'Compare one owned memory with its direct source'},
            {name:'Review Personal Memory',value:'personal_review',action:'Explicitly activate or archive one pinned owned memory'},
            {name:'Correct Personal Memory',value:'personal_correct',action:'Explicitly replace one owned memory and return it to candidate'},
            {name:'Get Context Before Turn',value:'before_turn',action:'Get memory context before an agent turn'},
            {name:'Save Consented Turn',value:'after_turn',action:'Save a consented conversation turn'},
            {name:'Get Session Status',value:'session_status',action:'Get the state of a saved turn'},
            {name:'Resume Project',value:'resume_project',action:'Load a project checkpoint'}]},
        {displayName:'Overview Scope',name:'overviewScope',type:'options',default:'',noDataExpression:true,
          displayOptions:{show:{operation:['personal_overview']}},options:[{name:'Select Scope',value:''},{name:'My Owned Records Across All Projects',value:'owned-all-projects'}],
          description:'Private metadata only. Source-root credential and observed instance/actor pins required. Not a project-filtered or shared-record count.'},
        {displayName:'Consent to Read Overview for This Item',name:'overviewConsent',type:'boolean',default:false,
          displayOptions:{show:{operation:['personal_overview']}},description:'Whether to read owner-wide statistics for this item. No bodies, model calls or memory writes. n8n execution history may retain the result.'},
        {displayName:'Candidate Scope',name:'candidateScope',type:'options',default:'',noDataExpression:true,
          displayOptions:{show:{operation:['personal_candidates']}},options:[{name:'Select Scope',value:''},{name:'Only My Global Candidates',value:'global-only'},
            {name:'My Global and Credential-Project Candidates',value:'global-and-project'}],
          description:'Only owned Agent-origin candidates. Project is fixed in the credential, never selected from item JSON. Not a total or database snapshot.'},
        {displayName:'Consent to Read Candidates for This Item',name:'candidateConsent',type:'boolean',default:false,
          displayOptions:{show:{operation:['personal_candidates']}},description:'Whether to read one private metadata page for this item. No bodies, writes or models. n8n execution history may retain the result.'},
        {displayName:'Candidate Page Size',name:'candidateLimit',type:'number',default:20,typeOptions:{minValue:1,maxValue:50},
          displayOptions:{show:{operation:['personal_candidates']}}},
        {displayName:'After Candidate ID',name:'candidateAfter',type:'string',default:'',
          displayOptions:{show:{operation:['personal_candidates']}},description:'Empty starts at the beginning. Otherwise explicitly supply next_after from a prior page with the same identity and scope. No auto-pagination or prefetch.'},
        {displayName:'Memory ID',name:'inspectMemoryId',type:'string',default:'',required:true,
          displayOptions:{show:{operation:['personal_inspect']}},description:'One exact lowercase UUID. No automatic source-following, candidate iteration or writes.'},
        {displayName:'Inspection Scope',name:'inspectScope',type:'options',default:'',noDataExpression:true,
          displayOptions:{show:{operation:['personal_inspect']}},options:[{name:'Select Scope',value:''},{name:'Only Global Records',value:'global-only'},
            {name:'Global and Credential Inspection Project',value:'global-and-project'}]},
        {displayName:'Consent to Read This Record',name:'inspectConsent',type:'boolean',default:false,
          displayOptions:{show:{operation:['personal_inspect']}},description:'Whether the full selected record may be transmitted to this adapter for validation. Project/owner filtering happens after transfer. No models or writes.'},
        {displayName:'Include Record Text in Output',name:'inspectIncludeText',type:'boolean',default:false,
          displayOptions:{show:{operation:['personal_inspect']}},description:'Whether to include body, provenance and stored reference. Otherwise output only metadata. n8n history/downstream nodes may retain outputs; text is untrusted data.'},
        {displayName:'Source Verification Memory ID',name:'lineageMemoryId',type:'string',default:'',
          displayOptions:{show:{operation:['personal_lineage']}},description:'One exact lowercase UUID. At most three full-record reads; no recursive source graph.'},
        {displayName:'Source Verification Scope',name:'lineageScope',type:'options',default:'',noDataExpression:true,
          options:[{name:'Select Scope',value:''},{name:'Global Only',value:'global-only'},{name:'Global and Credential Source-Verification Project',value:'global-and-project'}],
          displayOptions:{show:{operation:['personal_lineage']}}},
        {displayName:'Consent to Read Selected Memory',name:'lineageConsent',type:'boolean',default:false,noDataExpression:true,
          displayOptions:{show:{operation:['personal_lineage']}},description:'Whether the full selected record may be transmitted for verification, including a final re-read. Local scope checks happen after transfer.'},
        {displayName:'Consent to Read Its Direct Source',name:'lineageFollowConsent',type:'boolean',default:false,noDataExpression:true,
          displayOptions:{show:{operation:['personal_lineage']}},description:'Whether one stored source ID may be followed within the same credential scope. No writes, recursion, models or automatic approval. A matching quote is not proof of truth.'},
        {displayName:'Include Memory, Quote and Source Text',name:'lineageIncludeText',type:'boolean',default:false,
          displayOptions:{show:{operation:['personal_lineage']}},description:'Whether full texts and the stored quote appear in output. They are untrusted data and may be retained by n8n. Metadata-only output still requires full-record transfer.'},
        {displayName:'Review Mode',name:'reviewMode',type:'options',default:'',noDataExpression:true,options:[{name:'Select Mode',value:''},{name:'Apply Decision',value:'apply'},{name:'Recover Original Receipt Only',value:'replay'}],
          displayOptions:{show:{operation:['personal_review']}}},
        {displayName:'Decision',name:'reviewAction',type:'options',default:'',noDataExpression:true,options:[{name:'Select Decision',value:''},{name:'Activate After Review',value:'active'},{name:'Archive (Not Delete)',value:'archived'}],
          displayOptions:{show:{operation:['personal_review']}}},
        {displayName:'Reviewed Memory ID',name:'reviewMemoryId',type:'string',default:'',
          displayOptions:{show:{operation:['personal_review']}},description:'Exact lowercase UUID. One input item per execution; no bulk decisions.'},
        {displayName:'Review Scope',name:'reviewScope',type:'options',default:'',noDataExpression:true,options:[{name:'Select Scope',value:''},{name:'Global Only',value:'global-only'},{name:'Global and Credential Review Project',value:'global-and-project'}],
          displayOptions:{show:{operation:['personal_review']}}},
        {displayName:'Stable Review Event ID',name:'reviewEventId',type:'string',default:'',
          displayOptions:{show:{operation:['personal_review']}},description:'Keep the original event and all four server fields for receipt recovery. Never generate a new ID on an automatic retry.'},
        {displayName:'Reviewed Revision',name:'reviewExpectedRevision',type:'number',default:0,
          displayOptions:{show:{operation:['personal_review']}},description:'Copy the exact inspected revision. Zero is deliberately invalid; a stale version is refused.'},
        {displayName:'Reviewed Content SHA-256',name:'reviewExpectedHash',type:'string',default:'',
          displayOptions:{show:{operation:['personal_review']}},description:'Copy the complete lowercase content digest you inspected.'},
        {displayName:'Reviewed Status',name:'reviewExpectedStatus',type:'options',default:'',options:[{name:'Select Observed Status',value:''},{name:'Candidate',value:'candidate'},{name:'Active',value:'active'},{name:'Archived',value:'archived'}],
          displayOptions:{show:{operation:['personal_review']}}},
        {displayName:'Reviewed Visibility',name:'reviewExpectedVisibility',type:'options',default:'',options:[{name:'Select Observed Visibility',value:''},{name:'Private',value:'private'},{name:'Source Shared',value:'source'}],
          displayOptions:{show:{operation:['personal_review']}}},
        {displayName:'Reviewed Project ID',name:'reviewExpectedProject',type:'string',default:'',
          displayOptions:{show:{operation:['personal_review']}},description:'Empty means the inspected record was global. This is a precondition, not a grant to other projects.'},
        {displayName:'Explicitly Confirm This Exact Decision',name:'reviewConsent',type:'boolean',default:false,noDataExpression:true,
          displayOptions:{show:{operation:['personal_review']}},description:'Whether the caller reviewed this exact version and authorizes the selected action. This checkbox cannot authenticate a human reviewer.'},
        {displayName:'Acknowledge State Change and Full Read',name:'reviewAcknowledgeEffects',type:'boolean',default:false,noDataExpression:true,
          displayOptions:{show:{operation:['personal_review']}},description:'Whether to permit a full record read for verification and the selected state change. Activation enters recall; archive is not deletion. No automatic retries.'},
        {displayName:'Confirm Source-Shared Activation',name:'reviewSharedConsent',type:'boolean',default:false,noDataExpression:true,
          displayOptions:{show:{operation:['personal_review']}},description:'Whether activation of this source-shared record is explicitly approved. The credential must separately allow it; other source identities may then read it.'},
        {displayName:'Correction Mode',name:'correctMode',type:'options',default:'',noDataExpression:true,
          options:[{name:'Select Mode',value:''},{name:'Apply Complete Replacement',value:'apply'},{name:'Recover Original Correction Receipt',value:'replay'}],displayOptions:{show:{operation:['personal_correct']}}},
        {displayName:'Correction Memory ID',name:'correctMemoryId',type:'string',default:'',displayOptions:{show:{operation:['personal_correct']}},description:'Exact lowercase UUID. Exactly one input item per execution; never a batch of corrections.'},
        {displayName:'Correction Scope',name:'correctScope',type:'options',default:'',noDataExpression:true,
          options:[{name:'Select Scope',value:''},{name:'Global Only',value:'global-only'},{name:'Global and Credential Correction Project',value:'global-and-project'}],displayOptions:{show:{operation:['personal_correct']}}},
        {displayName:'Stable Correction Event ID',name:'correctEventId',type:'string',default:'',displayOptions:{show:{operation:['personal_correct']}},description:'Preserve this ID, the original revision and complete replacement for receipt recovery; never generate a new event automatically.'},
        {displayName:'Inspected Revision',name:'correctExpectedRevision',type:'number',default:0,displayOptions:{show:{operation:['personal_correct']}},description:'Exact observed revision; zero is intentionally invalid.'},
        {displayName:'Inspected Content SHA-256',name:'correctExpectedHash',type:'string',default:'',displayOptions:{show:{operation:['personal_correct']}}},
        {displayName:'Inspected Status',name:'correctExpectedStatus',type:'options',default:'',options:[{name:'Select Status',value:''},{name:'Candidate',value:'candidate'},{name:'Active',value:'active'},{name:'Archived',value:'archived'}],displayOptions:{show:{operation:['personal_correct']}}},
        {displayName:'Inspected Visibility',name:'correctExpectedVisibility',type:'options',default:'',options:[{name:'Select Visibility',value:''},{name:'Private',value:'private'},{name:'Source Shared',value:'source'}],displayOptions:{show:{operation:['personal_correct']}}},
        {displayName:'Inspected Project ID',name:'correctExpectedProject',type:'string',default:'',displayOptions:{show:{operation:['personal_correct']}},description:'Empty means the inspected record was global. Not an authorization grant.'},
        {displayName:'Complete Replacement JSON',name:'correctReplacement',type:'string',default:'',typeOptions:{rows:8},displayOptions:{show:{operation:['personal_correct']}},description:'Explicit JSON with exactly type, content, provenance, importance, confidence, visibility and project_id. No omitted defaults. Confidence/project may be null. n8n may retain parameter text; do not include secrets.'},
        {displayName:'Consent to This Complete Correction',name:'correctConsent',type:'boolean',default:false,noDataExpression:true,displayOptions:{show:{operation:['personal_correct']}},description:'Whether the caller authorizes this exact replacement. A checkbox does not authenticate a human reviewer.'},
        {displayName:'Acknowledge Full Read and Candidate Reset',name:'correctAcknowledgeReset',type:'boolean',default:false,noDataExpression:true,displayOptions:{show:{operation:['personal_correct']}},description:'Whether to read the full old record for validation and replace it. Correction resets status to candidate, clears derivation and last confirmation; reactivation is separate. Local scope checks happen after transfer.'},
        {displayName:'Confirm Project or Visibility Change',name:'correctScopeChangeConsent',type:'boolean',default:false,noDataExpression:true,displayOptions:{show:{operation:['personal_correct']}},description:'Whether the exact project/visibility change is approved. A separate credential grant is also required; source visibility does not automatically activate the record.'},
        {displayName:'Session ID',name:'sessionId',type:'string',default:'',required:true,
          displayOptions:{hide:{operation:['identity','personal_overview','personal_candidates','personal_inspect','personal_review','personal_correct','personal_lineage']}},description:'Stable application session ID, ASCII letters, numbers, underscore or hyphen; maximum 96 characters.'},
        {displayName:'Query',name:'query',type:'string',default:'',required:true,typeOptions:{rows:3},
          displayOptions:{show:{operation:['before_turn','resume_project']}}},
        {displayName:'Project ID',name:'projectId',type:'string',default:'',
          displayOptions:{show:{operation:['before_turn','resume_project']}},description:'Optional for context; required for Resume Project. The checkpoint must already exist.'},
        {displayName:'Event ID',name:'eventId',type:'string',default:'',required:true,
          displayOptions:{show:{operation:['after_turn','session_status']}},description:'Stable immutable ID from the producing app. Reuse the same ID and transcript for retries; do not derive it from a retry execution ID.'},
        {displayName:'Transcript',name:'transcript',type:'string',default:'',required:true,typeOptions:{rows:5},
          displayOptions:{show:{operation:['after_turn']}},description:'Already consented and redacted text, at most 64 KiB. No automatic capture or secret detection.'},
        {displayName:'Consent to Save This Item',name:'captureConsent',type:'boolean',default:false,
          displayOptions:{show:{operation:['after_turn']}},description:'Whether this item may be saved. The credential must also permit capture.'},
        {displayName:'Visibility',name:'visibility',type:'options',default:'private',
          displayOptions:{show:{operation:['after_turn']}},options:[{name:'Host Private',value:'private'},{name:'Shared Within Authorized Source',value:'world'}]},
        {displayName:'Memory Selection',name:'memoryPolicy',type:'options',default:'current',
          displayOptions:{show:{operation:['before_turn']}},options:[{name:'Current',value:'current'},{name:'Reviewed Only',value:'reviewed'},{name:'Explicit History',value:'history'}]},
        {displayName:'Summary Cache',name:'summary',type:'options',default:'prefer',
          displayOptions:{show:{operation:['before_turn']}},options:[{name:'Prefer Existing Summary',value:'prefer'},{name:'Require Existing Summary',value:'require'},{name:'Use Source Text',value:'off'}],description:'Never generates a summary or calls a model.'},
        {displayName:'Include Active Personal Memory',name:'includePersonal',type:'boolean',default:false,
          displayOptions:{show:{operation:['before_turn']}},description:'Whether to read explicitly active global and selected-project personal entries from this credential identity. Requires a source root and at least 4096 bytes.'},
        {displayName:'Include Governed Facts',name:'includeFacts',type:'boolean',default:false,
          displayOptions:{show:{operation:['before_turn']}},description:'Whether to combine current source-bound facts with pages; facts are not semantic matches to the query.'},
        {displayName:'Fact Entity',name:'factEntity',type:'string',default:'',
          displayOptions:{show:{operation:['before_turn'],includeFacts:[true]}},description:'Optional fixed entity. Empty uses native recent-fact selection.'},
        {displayName:'Evidence Budget (UTF-8 Bytes)',name:'budgetBytes',type:'number',default:16000,
          typeOptions:{minValue:512,maxValue:131072},displayOptions:{show:{operation:['before_turn']}},
          description:'Serialized evidence only, not model tokens or total prompt. At least 2048 with facts.'},
        {displayName:'Request Timeout (ms)',name:'timeoutMs',type:'number',default:30000,
          typeOptions:{minValue:1000,maxValue:120000}},
      ]};
  }
  async execute() {
    try{return [await runtime.execute(this)];}
    catch(e){
      const code=typeof e.code==='string'&&/^[a-z0-9_]{1,64}$/.test(e.code)?e.code:'adapter_failed';
      // Do not attach raw errors, input items, tokens or provider messages to n8n error reports.
      const outcome=['not_started','unconfirmed','confirmed'].includes(e.write_delivery)?`write_delivery=${e.write_delivery}; memory_writes_requested=${e.memory_writes_requested===true}`:e.memory_writes_requested===false?`read_delivery=${e.read_delivery==='unconfirmed'?'unconfirmed':'not_started'}; memory_writes_requested=false`:`delivery=${e.delivery==='unconfirmed'?'unconfirmed':'not_submitted'}`;
      throw new NodeOperationError(this.getNode(),`Ultrabrain: ${code}; ${outcome}`,
        {itemIndex:Number.isInteger(e.itemIndex)?e.itemIndex:0});
    }
  }
}
module.exports={Ultrabrain};
