#!/usr/bin/env python3
"""Plan/apply/rollback one native integration file. Never launch an Agent or change memory slots."""
import argparse
import importlib.util
import json
from pathlib import Path
import re
import sys

spec = importlib.util.spec_from_file_location('ultrabrain_config_io', Path(__file__).with_name('client-config.py'))
io = importlib.util.module_from_spec(spec)
spec.loader.exec_module(io)


def patch(kind, old, profile, library, node, cli, agents=(), sessions=()):
    if kind == 'opencode-native':
        # Local plugin contains exactly one exported factory; no shell or inline credentials.
        script = ('// Generated by Ultrabrain native-adapter-config; reviewed paths only.\n'
                  'import {createRequire} from "node:module";\n'
                  'const {createOpenCodePlugin}=createRequire(import.meta.url)(' + json.dumps(str(library)) + ');\n'
                  'export default createOpenCodePlugin({profilePath:' + json.dumps(str(profile)) + '});\n').encode()
        io.check(old is None or old == script, 'existing_plugin_conflict')
        return script
    if kind == 'hermes-native':
        entry = {'format': 1, 'node': str(node), 'cli': str(cli), 'profile': str(profile)}
        io.check(old is None or io.json_load(old) == entry, 'existing_provider_config_conflict')
        return old if old is not None else (json.dumps(entry, indent=2) + '\n').encode()
    io.check(kind == 'openclaw-native', 'unknown_native_adapter')
    for items in (agents, sessions):
        io.check(1 <= len(items) <= 32 and all(isinstance(v, str) and 0 < len(v) <= 256 and not re.search(r'[\x00-\x1f\x7f*]', v) for v in items), 'exact_agent_and_session_required')
    data = {} if old is None else io.json_load(old)
    io.check(isinstance(data, dict), 'object_config_required')
    plugins = data.setdefault('plugins', {})
    io.check(isinstance(plugins, dict) and plugins.get('enabled') is not False, 'plugins_disabled')
    deny = plugins.get('deny', [])
    io.check(isinstance(deny, list) and 'ultrabrain-personal' not in deny, 'plugin_explicitly_denied')
    allow = plugins.get('allow')
    if allow is not None:
        io.check(isinstance(allow, list), 'invalid_plugin_allowlist')
        if 'ultrabrain-personal' not in allow:
            allow.append('ultrabrain-personal')
    load = plugins.setdefault('load', {})
    io.check(isinstance(load, dict), 'invalid_plugin_load')
    paths = load.setdefault('paths', [])
    io.check(isinstance(paths, list), 'invalid_plugin_paths')
    package = str(library.parent.parent)
    if package not in paths:
        paths.append(package)
    entries = plugins.setdefault('entries', {})
    io.check(isinstance(entries, dict), 'invalid_plugin_entries')
    entry = {'enabled': True, 'config': {'profilePath': str(profile), 'agentIds': list(agents), 'sessionKeys': list(sessions)}}
    io.check('ultrabrain-personal' not in entries or entries['ultrabrain-personal'] == entry, 'existing_plugin_conflict')
    entries['ultrabrain-personal'] = entry
    # Never choose plugins.slots.memory or override any existing hook/tool policy.
    return old if old is not None and io.json_load(old) == data else (json.dumps(data, ensure_ascii=False, indent=2) + '\n').encode()


def main(argv=None):
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--client', choices=('opencode-native', 'openclaw-native', 'hermes-native'))
    for name in ('target', 'profile', 'library', 'node', 'cli', 'expected-sha', 'rollback'):
        p.add_argument('--' + name, required=name == 'target')
    p.add_argument('--agent-id', action='append', default=[])
    p.add_argument('--session-key', action='append', default=[])
    p.add_argument('--apply', action='store_true')
    a = p.parse_args(argv)
    lock_owned = False
    try:
        target = io.safe_path(a.target)
        lock = target.with_name(target.name + '.ultrabrain-config.lock')
        if a.rollback:
            io.check(not a.apply and not a.client, 'rollback_arguments_conflict')
            io.write_new(lock, b'local native adapter configuration\n'); lock_owned = True
            result = io.rollback(target, a.rollback)
        else:
            io.check(a.client and a.profile, 'client_and_profile_required')
            io.check(Path(a.profile).is_absolute(), 'absolute_profile_required')
            if a.client == 'opencode-native':
                io.check(target.suffix == '.js', 'opencode_plugin_js_required')
            for value in (a.library, a.node, a.cli):
                io.check(value is None or Path(value).is_absolute(), 'absolute_paths_required')
            profile = io.safe_path(a.profile)
            parsed = io.json_load(io.read_file(profile))
            io.check(parsed.get('format') == 1 and Path(parsed.get('workspace', '')).is_absolute(), 'bound_workspace_required')
            # Automatic hooks require explicit observed server and actor pins.
            io.check(bool(re.fullmatch(r'[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}', parsed.get('expected_instance', ''))) and
                     bool(re.fullmatch(r'[a-f0-9]{64}', parsed.get('expected_actor', ''))), 'probe_and_pin_profile_first')
            library = io.safe_path(a.library) if a.library else None
            node = io.safe_path(a.node) if a.node else None
            cli = io.safe_path(a.cli) if a.cli else None
            if a.client == 'hermes-native':
                io.check(node is not None and node.is_file() and cli is not None and cli.is_file(), 'node_and_cli_required')
            else:
                io.check(library is not None and library.name == 'native-adapters.cjs' and library.is_file(), 'native_adapter_library_required')
            if a.client == 'openclaw-native':
                manifest = io.json_load(io.read_file(library.parent.parent / 'openclaw.plugin.json'))
                io.check(manifest.get('id') == 'ultrabrain-personal', 'wrong_plugin_package')
            old = io.read_file(target)
            new = patch(a.client, old, profile, library, node, cli, a.agent_id, a.session_key)
            result = {'client': a.client, 'mode': 'plan', 'changed': old != new,
                      'before_sha256': 'absent' if old is None else io.digest(old), 'after_sha256': io.digest(new),
                      'capture_enabled_by_adapter': a.client=='opencode-native' and any(x in ('opencode-user','opencode-assistant') for x in parsed.get('automatic_capture',[])), 'changes_existing_memory_slot': False}
            if a.apply:
                io.write_new(lock, b'local native adapter configuration\n'); lock_owned = True
                result.update(io.apply(target, old, new, a.expected_sha)); result['mode'] = 'applied'
        print(json.dumps(result, indent=2)); return 0
    except Exception as error:
        print(json.dumps({'ok': False, 'error': str(error) if isinstance(error, io.ConfigError) else 'native_config_failed'})); return 1
    finally:
        if lock_owned:
            lock.unlink(missing_ok=True)


if __name__ == '__main__':
    sys.exit(main())
